dataformCoreVersion: 3.0.0

defaultLocation: dummy

defaultProject: dummy
defaultDataset: dummy
defaultAssertionDataset: dummy

vars:
  raw_dataset: raw_data
  analytics_dataset: clean_data
  mart_dataset: clean_data_mart
  assertion_dataset: clean_data_assertions
  client_id: client_a